---
name: deploy to gh pages

on:
  push:
    branches:
      - main
    paths:
      - pages/**

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    uses: techtales-io/github-workflows/.github/workflows/deploy-gh-pages.yaml@ecc2ec9aad03311eae6f69ac571430fcdc773211 # v0.5.8
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      runner: ubuntu-latest
      environment: github-pages
      path: pages
