---
name: deploy to gh pages

on:
  push:
    branches:
      - main
    paths:
      - pages/**

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    uses: techtales-io/github-workflows/.github/workflows/deploy-gh-pages.yaml@32543b44ee214e89e422e08707b010d6a6b29451 # v0.5.2
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      runner: ubuntu-latest
      environment: github-pages
      path: pages
