---
name: deploy to gh pages

on:
  push:
    branches:
      - main
    paths:
      - pages/**

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    uses: techtales-io/github-workflows/.github/workflows/deploy-gh-pages.yaml@a456be77f7ef4b465b4fdd3dd426f47588cd9e49 # v0.5.1
    permissions:
      contents: read
      pages: write
      id-token: write
    with:
      runner: ubuntu-latest
      environment: github-pages
      path: pages
